Dapp-Learning-DAO/Official-website-backend

interface/member.json
src/main/java/com/dl/officialsite/File/FileController.java

feat:文件上传功能

---

src/main/java/com/dl/officialsite/File/FileController.java
src/main/java/com/dl/officialsite/common/base/BaseResponse.java
src/main/java/com/dl/officialsite/common/enums/CodeEnums.java
src/main/java/com/dl/officialsite/common/exception/BizException.java

feat:封装错误码和自定义异常

---

interface/member.json

feat:添加更新头像接口

---

src/main/java/com/dl/officialsite/File/FileController.java
src/main/java/com/dl/officialsite/common/advice/ExceptionHandlerAdvice.java
src/main/java/com/dl/officialsite/common/constants/Constants.java
src/main/java/com/dl/officialsite/common/enums/CodeEnums.java
src/main/java/com/dl/officialsite/ipfs/IPFSService.java
src/main/java/com/dl/officialsite/team/Team.java
src/main/java/com/dl/officialsite/team/TeamController.java
src/main/java/com/dl/officialsite/team/TeamMember.java
src/main/java/com/dl/officialsite/team/TeamMemberRepository.java
src/main/java/com/dl/officialsite/team/TeamRepository.java
src/main/java/com/dl/officialsite/team/TeamService.java
src/main/java/com/dl/officialsite/team/vo/TeamMemberApproveVO.java
src/main/java/com/dl/officialsite/team/vo/TeamMemberJoinVO.java
src/main/java/com/dl/officialsite/team/vo/TeamQueryVo.java
src/main/java/com/dl/officialsite/team/vo/TeamVO.java
src/main/java/com/dl/officialsite/team/vo/TeamsMembersVo.java

fix:修改文件下载逻辑

---

src/main/java/com/dl/officialsite/common/enums/CodeEnums.java
src/main/java/com/dl/officialsite/team/TeamController.java
src/main/java/com/dl/officialsite/team/TeamService.java

feat:add function get member Teams

feat:add function get member Teams

---

src/main/resources/application.yml

fix： update port

---

src/main/resources/application-template.yml

fix： update application-template.yml email config

fix： update application-template.yml email config

---

src/main/java/com/dl/officialsite/team/TeamService.java

fix： edit approve function

---

src/main/java/com/dl/officialsite/team/TeamService.java

fix: 修改成员退出团队在加入的逻辑

---

src/main/java/com/dl/officialsite/common/constants/Constants.java
src/main/java/com/dl/officialsite/common/enums/CodeEnums.java
src/main/java/com/dl/officialsite/config/SecurityConfig.java
src/main/java/com/dl/officialsite/hiring/HireController.java
src/main/java/com/dl/officialsite/hiring/HireRepository.java
src/main/java/com/dl/officialsite/hiring/HireService.java
src/main/java/com/dl/officialsite/hiring/Hiring.java
src/main/java/com/dl/officialsite/hiring/HiringSkill.java
src/main/java/com/dl/officialsite/hiring/HiringSkillRepository.java
src/main/java/com/dl/officialsite/hiring/vo/HiringVO.java
src/main/java/com/dl/officialsite/mail/EmailService.java

feat:添加招聘模块

---

README.md
src/main/java/com/dl/officialsite/OfficialSiteApplication.java
src/main/java/com/dl/officialsite/hiring/HireController.java
src/main/java/com/dl/officialsite/hiring/HireService.java
src/main/java/com/dl/officialsite/hiring/HiringSkillRepository.java
src/main/java/com/dl/officialsite/hiring/vo/HiringSkillVO.java
src/main/java/com/dl/officialsite/hiring/vo/HiringVO.java
src/main/java/com/dl/officialsite/redpacket/RedPacketService.java
src/main/java/com/dl/officialsite/team/TeamController.java
src/main/java/com/dl/officialsite/team/TeamService.java
src/main/java/com/dl/officialsite/team/vo/TeamMemberBatchJoinVO.java

feat:添加招聘模块的update,批量更新,批量添加成员

feat:添加招聘模块的update,批量更新,批量添加成员

---

src/main/java/com/dl/officialsite/sharing/controller/UserSharingController.java
src/main/java/com/dl/officialsite/team/TeamController.java
src/main/java/com/dl/officialsite/team/TeamService.java
src/main/java/com/dl/officialsite/team/teammember/TeamMemberRepository.java

fix：修改批量加入代码

---

src/main/java/com/dl/officialsite/common/constants/Constants.java
src/main/java/com/dl/officialsite/hiring/HireController.java
src/main/java/com/dl/officialsite/hiring/HireRepository.java
src/main/java/com/dl/officialsite/hiring/HireService.java
src/main/java/com/dl/officialsite/hiring/Hiring.java
src/main/java/com/dl/officialsite/hiring/HiringSkill.java
src/main/java/com/dl/officialsite/hiring/HiringSkillRepository.java
src/main/java/com/dl/officialsite/hiring/application/Application.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationController.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationService.java
src/main/java/com/dl/officialsite/hiring/vo/ApplyVo.java
src/main/java/com/dl/officialsite/hiring/vo/HiringSkillVO.java
src/main/java/com/dl/officialsite/hiring/vo/HiringVO.java
src/main/java/com/dl/officialsite/member/MemberRepository.java
src/main/java/com/dl/officialsite/team/TeamService.java
src/main/java/com/dl/officialsite/team/vo/TeamMemberBatchJoinVO.java

feat：完成todo.修改招聘模块

---

src/main/java/com/dl/officialsite/hiring/HireService.java

fix:优化招聘类代码

---

src/main/java/com/dl/officialsite/team/vo/TeamMemberJoinVO.java

fix:解决memberID 和teamid为null问题

---

src/main/java/com/dl/officialsite/OfficialSiteApplication.java
src/main/java/com/dl/officialsite/common/enums/CodeEnums.java
src/main/java/com/dl/officialsite/team/TeamController.java
src/main/java/com/dl/officialsite/team/TeamService.java
src/main/java/com/dl/officialsite/team/teammember/TeamMemberRepository.java

[feat:增加删除团队功能](https://github.com/Dapp-Learning-DAO/Official-website-backend/commit/9763fc0558d056514ee5b2606cb1a7e1f0bf3d4e)

feat:增加删除团队功能

---

src/main/java/com/dl/officialsite/team/Team.java
src/main/java/com/dl/officialsite/team/TeamController.java
src/main/java/com/dl/officialsite/team/TeamService.java
src/main/java/com/dl/officialsite/team/teammember/TeamMemberRepository.java

fix:删除teammember

---

src/main/resources/application.yml
src/test/java/com/dl/officialsite/OfficialSiteApplicationTests.java

Refer to https://stackoverflow.com/a/77074075

Change mail to Gmail

---

src/main/java/com/dl/officialsite/hiring/HireController.java
src/main/java/com/dl/officialsite/hiring/HireService.java
src/main/java/com/dl/officialsite/member/MemberWithTeam.java
src/main/java/com/dl/officialsite/team/TeamRepository.java

fix:解决添加招聘需要hiring,sharing权限问题

fix:解决添加招聘需要hiring,sharing权限问题

---

src/main/java/com/dl/officialsite/hiring/Hiring.java
src/main/java/com/dl/officialsite/hiring/application/Application.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationController.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationService.java
src/main/java/com/dl/officialsite/hiring/vo/ApplySearchVo.java
src/main/resources/DB/1.SQL

feat:新增查询条件查询所有岗位

---

src/main/java/com/dl/officialsite/common/constants/Constants.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationService.java
src/main/java/com/dl/officialsite/reward/RewardService.java

1.get application list with 502

fix: get application list with 502

---

src/main/java/com/dl/officialsite/common/enums/CodeEnums.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationRepository.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationService.java
src/main/java/com/dl/officialsite/redpacket/RedPacketService.java
src/main/java/com/dl/officialsite/reward/RewardService.java

1. add constants
2. add snippet for jsonResponse errors

add code snippet

---

deploy/docker-compose-backend-app.yaml
src/main/java/com/dl/officialsite/config/ChainConfig.java
src/main/java/com/dl/officialsite/redpacket/RedPacketService.java
src/main/java/com/dl/officialsite/reward/RewardService.java
src/main/resources/application-dev.yml
src/main/resources/logback-spring.xml

1. Splite the task logs
2. add application-dev.yml
3. update deploy docker-compose.yml

Optimize logs

---

src/main/java/com/dl/officialsite/bounty/BountyController.java
src/main/java/com/dl/officialsite/bounty/BountyRepository.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/BountySearchVo.java
src/main/java/com/dl/officialsite/bounty/vo/BountyVo.java
src/main/java/com/dl/officialsite/common/constants/Constants.java
src/main/java/com/dl/officialsite/common/enums/CodeEnums.java
src/main/java/com/dl/officialsite/hiring/Hiring.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationController.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationService.java

feat: bounty add update delete detail

feat: bounty add update delete detail

---

.gitignore
src/main/java/com/dl/officialsite/bounty/BountyController.java
src/main/java/com/dl/officialsite/bounty/BountyService.java

fix: update restful interface

---

build.gradle
deploy/docker-compose-backend-app.yaml
src/main/java/com/dl/officialsite/bot/telegram/TelegramBotConfig.java
src/main/java/com/dl/officialsite/bot/telegram/TelegramBotController.java
src/main/java/com/dl/officialsite/bot/telegram/TelegramBotService.java
src/main/java/com/dl/officialsite/bot/telegram/TelegramBotUtil.java
src/main/resources/application.yml
src/test/java/com/dl/officialsite/OfficialSiteApplicationTests.java

1. Send message with Markdown_V2
2. Add test controller only activate in `dev` and `local`.

Add Telegram API support

---

.gitignore
src/main/java/com/dl/officialsite/bot/telegram/TelegramBotConfig.java
src/main/java/com/dl/officialsite/bounty/BountyController.java
src/main/java/com/dl/officialsite/bounty/BountyMemberMap.java
src/main/java/com/dl/officialsite/bounty/BountyMemberMapRepository.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/MyBountySearchVo.java
src/main/java/com/dl/officialsite/common/constants/Constants.java

feat: add apply bounty
add query mybounty

feat: add apply bounty

---

src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/BountyVo.java
src/main/java/com/dl/officialsite/bounty/vo/MyBountySearchVo.java
src/main/java/com/dl/officialsite/redpacket/RedPacketService.java

fix: delete disable code

---

src/main/java/com/dl/officialsite/bounty/BountyController.java
src/main/java/com/dl/officialsite/bounty/BountyMemberMapRepository.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/BountyVo.java

feta: apply status update

---

src/main/java/com/dl/officialsite/bounty/BountyController.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/BountyMemberVo.java

feta: is apply bounty

---

src/main/java/com/dl/officialsite/bounty/BountyController.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/ApplyBountyVo.java

feta: update ApplyBountyVo

---

src/main/java/com/dl/officialsite/distributor/DistributeInfo.java
src/main/java/com/dl/officialsite/distributor/distributeClaimer/DistributeClaimer.java

change index

---

src/main/java/com/dl/officialsite/common/enums/DistributeClaimerStatusEnums.java
src/main/java/com/dl/officialsite/distributor/DistributeController.java
src/main/java/com/dl/officialsite/distributor/DistributeInfo.java
src/main/java/com/dl/officialsite/distributor/DistributeRepository.java
src/main/java/com/dl/officialsite/distributor/DistributeService.java
src/main/java/com/dl/officialsite/distributor/distributeClaimer/DistributeClaimerRepository.java
src/main/java/com/dl/officialsite/distributor/distributeClaimer/DistributeClaimerService.java
src/main/java/com/dl/officialsite/distributor/vo/AddDistributeClaimerReqVo.java
src/main/java/com/dl/officialsite/distributor/vo/DistributeInfoVo.java

support query distribute by claimer and status

update interface of distribute: support queries by claimer and status

---

src/main/java/com/dl/officialsite/common/enums/DistributeStatusEnums.java
src/main/java/com/dl/officialsite/distributor/DistributeInfo.java
src/main/java/com/dl/officialsite/distributor/DistributeManager.java
src/main/java/com/dl/officialsite/distributor/DistributeRepository.java
src/main/java/com/dl/officialsite/distributor/DistributeService.java
src/main/java/com/dl/officialsite/distributor/distributeClaimer/DistributeClaimerController.java

update status list of distribute

update status list of distribute

---

src/main/java/com/dl/officialsite/bot/discord/DiscordBotService.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/BountySearchVo.java

feta: add BountySearchVo query condition

feta: add BountySearchVo query condition

---

src/main/java/com/dl/officialsite/distributor/DistributeService.java
src/main/java/com/dl/officialsite/distributor/distributeClaimer/DistributeClaimer.java
src/main/resources/application.yml
src/main/resources/logback-spring.xml

The distribute amount supports 18 precision

The distribute amount supports 18 precision

---

src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/BountyVo.java

feta: add creator detail info in BountyVo

feta: add creator detail info in BountyVo

---

src/main/java/com/dl/officialsite/distributor/DistributeService.java

Distribute support multi chain

Distribute support multi chain

---

src/main/java/com/dl/officialsite/sharing/Share.java
src/main/java/com/dl/officialsite/sharing/SharingController.java
src/main/java/com/dl/officialsite/sharing/SharingService.java
src/main/java/com/dl/officialsite/sharing/constant/SharingStatus.java

feta: add approve share and finish share

feta: add approve share and finish share

---

src/main/java/com/dl/officialsite/bounty/BountyService.java

feta: add creator info in bounty detail

feta: add creator info in bounty detail

---

src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/sharing/SharingService.java

fix: add sharing theme to mail content

fix: add sharing theme to mail content

---

src/main/java/com/dl/officialsite/bounty/BountyService.java

feat: add bounty detail member info

feat: add bounty detail member info

---

src/main/java/com/dl/officialsite/bounty/Bounty.java
src/main/java/com/dl/officialsite/bounty/BountyController.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/BountyVo.java

feat: add link bounty and stream pay

feat: add link bounty and stream pay

---

src/main/java/com/dl/officialsite/sharing/Share.java
src/main/java/com/dl/officialsite/sharing/ShareSearchVo.java
src/main/java/com/dl/officialsite/sharing/SharingController.java
src/main/java/com/dl/officialsite/sharing/SharingService.java
src/main/java/com/dl/officialsite/sharing/model/req/UpdateSharingReq.java

feat: share condition query

---

src/main/java/com/dl/officialsite/OfficialSiteApplication.java
src/main/java/com/dl/officialsite/bot/constant/BotEnum.java
src/main/java/com/dl/officialsite/bot/constant/ChannelEnum.java
src/main/java/com/dl/officialsite/bot/discord/DiscordBotConfig.java
src/main/java/com/dl/officialsite/bot/discord/DiscordBotController.java
src/main/java/com/dl/officialsite/bot/discord/DiscordBotService.java
src/main/java/com/dl/officialsite/bot/event/EventNotify.java
src/main/java/com/dl/officialsite/bot/event/NotifyEventListener.java
src/main/java/com/dl/officialsite/bot/telegram/TelegramBotConfig.java
src/main/java/com/dl/officialsite/bot/telegram/TelegramBotController.java
src/main/java/com/dl/officialsite/bot/telegram/TelegramBotService.java
src/main/java/com/dl/officialsite/bot/telegram/TelegramBotUtil.java
src/main/java/com/dl/officialsite/bot/telegram/TelegramMarkdownV2Escaper.java
src/main/java/com/dl/officialsite/member/MemberService.java

1. Don't load Telegram and Discord if the bot.xxx configuration is not configured.
2. Send message when user registered.

Update event notify

---

build.gradle
src/main/java/com/dl/officialsite/bot/event/NotifyEventListener.java

[remove api more than jdk 8](https://github.com/Dapp-Learning-DAO/Official-website-backend/commit/b746aece1336ed7319f29e18aa36e605f43809af)

remove api more than jdk 8

---

src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/BountySearchVo.java
src/main/java/com/dl/officialsite/sharing/Share.java
src/main/java/com/dl/officialsite/sharing/model/req/UpdateSharingReq.java

fix: update share entity time type date to string

fix: update share entity time type date to string

---

src/main/java/com/dl/officialsite/bounty/Bounty.java
src/main/java/com/dl/officialsite/bounty/BountyController.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/BountySearchVo.java
src/main/java/com/dl/officialsite/bounty/vo/BountyVo.java
src/main/java/com/dl/officialsite/sharing/Share.java
src/main/java/com/dl/officialsite/sharing/SharingController.java
src/main/java/com/dl/officialsite/sharing/SharingRepository.java
src/main/java/com/dl/officialsite/sharing/SharingService.java
src/main/java/com/dl/officialsite/sharing/model/bo/RankDto.java

feat: share rank top 3

---

src/main/java/com/dl/officialsite/aave/Constant.java
src/main/java/com/dl/officialsite/bounty/BountyController.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/member/MemberController.java
src/main/java/com/dl/officialsite/sharing/SharingService.java
src/main/java/com/dl/officialsite/team/TeamService.java

add team ,exit team send message to tel
new bounty send message to tel
new share send message to tel

feat: send messaget to tel

---

src/main/resources/DB/3.sql
src/main/resources/application.yml

update share data and close sql log

update share data and close sql log

---

src/main/java/com/dl/officialsite/bounty/Bounty.java
src/main/java/com/dl/officialsite/bounty/vo/BountyVo.java

fix: update LocalDateTime to Long

fix: update LocalDateTime to Long

---

src/main/java/com/dl/officialsite/aave/AaveService.java
src/main/java/com/dl/officialsite/aave/AaveTokenAPYInfo.java
src/main/java/com/dl/officialsite/aave/AbstractTokenAPY.java
src/main/java/com/dl/officialsite/aave/DeFiController.java
src/main/java/com/dl/officialsite/aave/DeFiTokenYield.java
src/main/java/com/dl/officialsite/aave/TokenAPYInfo.java
src/main/java/com/dl/officialsite/bot/discord/DiscordBotConfig.java
src/main/java/com/dl/officialsite/bounty/vo/BountyVo.java
src/main/resources/logback-spring.xml

feat: developing defi module partial function

feat: developing defi module partial function

---

src/main/resources/logback-spring.xml

fix: update logback-spring.xml aave-defi-minitor

fix: update logback-spring.xml aave-defi-minitor

---

src/main/java/com/dl/officialsite/login/filter/LoginFilter.java

fix:login filter add "share/all" "share/rank"

fix:login filter add "share/all" "share/rank"

---

src/main/java/com/dl/officialsite/aave/AaveTokenAPYService.java
src/main/java/com/dl/officialsite/aave/DeFiController.java

feat: get all chainName

---

src/main/java/com/dl/officialsite/aave/AaveService.java
src/main/java/com/dl/officialsite/aave/DeFiTokenYield.java
src/main/java/com/dl/officialsite/config/NetworkProperties.java
src/main/java/com/dl/officialsite/config/Web3jAutoConfiguration.java
src/main/resources/application.yml

Configure web3j for each chain

Configure web3j for each chain

---

src/main/java/com/dl/officialsite/aave/AaveTokenAPYService.java
src/main/java/com/dl/officialsite/aave/Constant.java
src/main/java/com/dl/officialsite/config/Web3jAutoConfiguration.java

Initialization of web3j

---

src/main/java/com/dl/officialsite/aave/AaveTokenAPYService.java
src/main/java/com/dl/officialsite/aave/AbstractTokenAPY.java
src/main/java/com/dl/officialsite/aave/DeFiController.java
src/main/java/com/dl/officialsite/aave/TokenAPYInfo.java
src/main/java/com/dl/officialsite/aave/TokenAPYInfoRepository.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/vo/BountySearchVo.java
src/main/java/com/dl/officialsite/common/enums/CodeEnums.java
src/main/java/com/dl/officialsite/config/ChainInfo.java
src/main/java/com/dl/officialsite/config/TokenConfig.java
src/main/java/com/dl/officialsite/config/Web3jAutoConfiguration.java
src/main/resources/application-dev.yml
src/main/resources/application.yml

feat: get token apy

---

src/main/java/com/dl/officialsite/aave/Constant.java
src/main/java/com/dl/officialsite/bot/event/EventNotify.java
src/main/java/com/dl/officialsite/common/constants/Constants.java
src/main/java/com/dl/officialsite/config/ChainInfo.java
src/main/java/com/dl/officialsite/config/TokenConfig.java
src/main/java/com/dl/officialsite/config/Web3jAutoConfiguration.java

add address of aave pool

---

src/main/java/com/dl/officialsite/aave/constants/Constant.java
src/main/java/com/dl/officialsite/aave/service/AaveTokenAPYService.java

feat: add usdc.e token info

---

src/main/java/com/dl/officialsite/aave/constants/Constant.java
src/main/java/com/dl/officialsite/aave/service/AaveTokenAPYService.java
src/main/java/com/dl/officialsite/distributor/DistributeService.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationController.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationHiringDetailVo.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationService.java
src/main/java/com/dl/officialsite/login/filter/LoginFilter.java
src/main/java/com/dl/officialsite/member/MemberService.java
src/main/java/com/dl/officialsite/redpacket/RedPacketService.java
src/main/resources/application-dev.yml

feat: not filter defi api

---

src/main/java/com/dl/officialsite/oauth2/controller/TwitterController.java

fix: update return "/oauth2/callback/twitter"

fix: update return "/oauth2/callback/twitter"

---

src/main/java/com/dl/officialsite/member/MemberVo.java

fix member profile twitter callback

fix member profile twitter callback 

---

src/main/java/com/dl/officialsite/admin/AdminController.java
src/main/java/com/dl/officialsite/admin/AdminService.java
src/main/java/com/dl/officialsite/admin/vo/HireSearchParams.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/hiring/HireService.java
src/main/java/com/dl/officialsite/hiring/Hiring.java
src/main/java/com/dl/officialsite/member/Member.java
src/main/java/com/dl/officialsite/member/MemberService.java

1. get all hire
2. delete hire
3. gei all bounty
4. freeze member

feat: admin

---

src/main/java/com/dl/officialsite/aave/constants/Constant.java

feat: add LUSD defi apy monitor

feat: add LUSD defi apy monitor

---

src/main/java/com/dl/officialsite/admin/AdminController.java
src/main/java/com/dl/officialsite/hiring/HireService.java

fix: add page function for get hiring list

fix: add page function for get hiring list

---

src/main/java/com/dl/officialsite/aave/Constant.java
src/main/java/com/dl/officialsite/aave/constants/Constant.java
src/main/java/com/dl/officialsite/common/constants/Constants.java
src/main/java/com/dl/officialsite/distributor/DistributeService.java
src/main/java/com/dl/officialsite/redpacket/RedPacketService.java
src/main/resources/application.yml

New support chain

---

src/main/resources/application.yml

1. add placeholder for spring data jpa batch insert

 add placeholder 

---

src/main/java/com/dl/officialsite/defi/controller/DeFiController.java
src/main/java/com/dl/officialsite/defi/dao/WhaleRepository.java
src/main/java/com/dl/officialsite/defi/service/WhaleService.java

fix: whale data save database

---

src/main/java/com/dl/officialsite/defi/controller/DeFiController.java
src/main/java/com/dl/officialsite/defi/entity/Whale.java
src/main/java/com/dl/officialsite/defi/service/WhaleService.java
src/main/java/com/dl/officialsite/defi/vo/params/QueryWhaleParams.java

1. add controller query whale tx
2. add convertUnit function

fix bug and add feat

---

src/main/java/com/dl/officialsite/login/filter/LoginFilter.java
src/main/resources/application.yml

feat: add debank url

---

src/main/java/com/dl/officialsite/defi/controller/DeFiController.java
src/main/java/com/dl/officialsite/defi/dao/WhaleProtocolRepository.java
src/main/java/com/dl/officialsite/defi/entity/WhaleProtocol.java
src/main/java/com/dl/officialsite/defi/service/WhaleProtocolService.java
src/main/java/com/dl/officialsite/defi/service/WhaleService.java

add whale protocol feat

---

src/main/java/com/dl/officialsite/sharing/SharingController.java
src/main/java/com/dl/officialsite/sharing/SharingService.java

fix: share function not condition search

fix: share function not condition search

---

src/main/java/com/dl/officialsite/sharing/SharingService.java

fix: edit share not send msg to telegram

fix: edit share not send msg to telegram

---

src/main/java/com/dl/officialsite/config/constant/ConfigEnum.java
src/main/java/com/dl/officialsite/defi/controller/DeFiController.java
src/main/java/com/dl/officialsite/defi/handler/AaveWhaleProtocolHandler.java
src/main/java/com/dl/officialsite/defi/handler/AbstractWhaleProtocolHandler.java
src/main/java/com/dl/officialsite/defi/handler/CompoundWhaleProtocolHandler.java
src/main/java/com/dl/officialsite/defi/service/WhaleProtocolService.java
src/main/java/com/dl/officialsite/distributor/DistributeService.java
src/main/java/com/dl/officialsite/distributor/config/MerkleDistributorConfig.java
src/main/java/com/dl/officialsite/redpacket/RedPacketService.java
src/main/java/com/dl/officialsite/redpacket/config/BaseGraph.java
src/main/java/com/dl/officialsite/redpacket/config/GraphConfig.java
src/main/java/com/dl/officialsite/redpacket/config/RedPacketConfig.java
src/main/java/com/dl/officialsite/sharing/SharingService.java
src/main/java/com/dl/officialsite/sharing/model/resp/ShareVo.java

update graph key

---

src/main/java/com/dl/officialsite/distributor/DistributeService.java
src/main/java/com/dl/officialsite/redpacket/RedPacketService.java

down the frenqucy of schedule task

down the frenqucy of schedule task

---

src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/hiring/application/ApplicationService.java
src/main/java/com/dl/officialsite/mail/EmailService.java

feat:1. add send mail for apply bounty    
2. cc mail to dapp official mail
3. fix hiring bug when send mail

Add feature and fix bug

---

src/main/java/com/dl/officialsite/admin/AdminController.java
src/main/java/com/dl/officialsite/bounty/BountyController.java
src/main/java/com/dl/officialsite/hiring/HireController.java
src/main/java/com/dl/officialsite/login/filter/LoginFilter.java

remove some permission check

---

src/main/java/com/dl/officialsite/defi/service/WhaleService.java

add empty check

---

src/main/java/com/dl/officialsite/redpacket/RedPacketService.java

replace redpacket graph url for op and arb

fix: replace redpacket graph url for op and arb

---

src/main/java/com/dl/officialsite/redpacket/RedPacketService.java

replace redpacket graph url for op

fix: replace redpacket graph url for op

---

src/main/java/com/dl/officialsite/redpacket/RedPacketController.java

fix: require body is missing

---

src/main/java/com/dl/officialsite/redpacket/RedPacketController.java

fix: require request body is missing

fix: require request body is missing

---

src/main/java/com/dl/officialsite/redpacket/RedPacketController.java
src/main/resources/application.yml

feat: add xxl-job executor appname is env

feat: add xxl-job executor appname is env

---

src/main/java/com/dl/officialsite/login/filter/LoginFilter.java
src/main/java/com/dl/officialsite/sponsor/SponsorController.java

remove share-search permission check

remove share-search permission check

---

src/main/java/com/dl/officialsite/redpacket/RedPacketService.java

add sepolia scroll zksync graph url

fix: redPacket

---

src/main/java/com/dl/officialsite/redpacket/RedPacketService.java

fix: update zksync redpacket graph url

fix: update zksync redpacket graph url

---

src/main/java/com/dl/officialsite/config/constant/ConfigEnum.java
src/main/java/com/dl/officialsite/member/MemberService.java
src/main/java/com/dl/officialsite/member/job/MemberXxlJob.java
src/main/java/com/dl/officialsite/sharing/Share.java
src/main/java/com/dl/officialsite/sharing/ShareSearchVo.java
src/main/java/com/dl/officialsite/sharing/SharingController.java
src/main/java/com/dl/officialsite/sharing/SharingService.java
src/main/java/com/dl/officialsite/sharing/config/ShareTagConfigService.java
src/main/java/com/dl/officialsite/sharing/model/resp/ShareTagResp.java

add share tag

---

src/main/java/com/dl/officialsite/mail/EmailService.java
src/main/java/com/dl/officialsite/redpacket/RedPacketController.java
src/main/java/com/dl/officialsite/sharing/Share.java
src/main/java/com/dl/officialsite/sharing/SharingService.java

feat:1.Add outline property 2. send mail when new share

feat:1.Add outline property 2. send mail when new share

---

src/main/java/com/dl/officialsite/mail/EmailService.java
src/main/java/com/dl/officialsite/redpacket/RedPacketController.java
src/main/java/com/dl/officialsite/sharing/Share.java
src/main/java/com/dl/officialsite/sharing/SharingService.java

Reverts Dapp-Learning-DAO/Official-website-backend#304

Revert "feat:1.Add outline property 2. send mail when new share"

---

src/main/java/com/dl/officialsite/mail/EmailService.java
src/main/java/com/dl/officialsite/sharing/Share.java
src/main/java/com/dl/officialsite/sharing/SharingService.java

fix: fix course and share conflict

fix: fix course and share conflict

---

src/main/java/com/dl/officialsite/sharing/SharingService.java
src/main/java/com/dl/officialsite/sharing/model/req/UpdateSharingReq.java

feat: add outline for updating share

feat: add outline for updating share

---

src/main/java/com/dl/officialsite/bounty/BountyController.java
src/main/java/com/dl/officialsite/bounty/BountyMemberMap.java
src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/bounty/params/ApplyBountyParam.java
src/main/java/com/dl/officialsite/wish/Wish.java
src/main/java/com/dl/officialsite/wish/WishController.java
src/main/java/com/dl/officialsite/wish/WishRepository.java
src/main/java/com/dl/officialsite/wish/WishService.java
src/main/java/com/dl/officialsite/wish/package-info.java
src/main/java/com/dl/officialsite/wish/params/AddWishParam.java
src/main/java/com/dl/officialsite/wish/result/WishDetailResult.java

feat: add contractAddress and introduction

feat: add contractAddress and introduction

---

src/main/java/com/dl/officialsite/bounty/vo/BountyMemberVo.java
src/main/java/com/dl/officialsite/distributor/DistributeService.java
src/main/java/com/dl/officialsite/mail/EmailService.java
src/main/java/com/dl/officialsite/redpacket/RedPacketService.java
src/main/java/com/dl/officialsite/sharing/SharingService.java

fix: 1.update redpacket graph

---

src/main/java/com/dl/officialsite/bounty/params/ApplyBountyParam.java

feat:1.cancel ApplyBountyParam

feat:1.cancel ApplyBountyParam

---

src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/sharing/SharingService.java

fix:1.update Share Email template 2.update Bounty Email template

fix:1.update Share Email template 2.update Bounty Email template

---

src/main/java/com/dl/officialsite/bounty/BountyService.java
src/main/java/com/dl/officialsite/common/enums/CodeEnums.java
src/main/java/com/dl/officialsite/sharing/SharingController.java
src/main/java/com/dl/officialsite/wish/WishController.java
src/main/java/com/dl/officialsite/wish/WishLike.java
src/main/java/com/dl/officialsite/wish/WishLikeRepository.java
src/main/java/com/dl/officialsite/wish/WishService.java
src/main/java/com/dl/officialsite/wish/params/AddWishParam.java
src/main/java/com/dl/officialsite/wish/params/EditWishParam.java
src/main/java/com/dl/officialsite/wish/params/QueryWishParam.java
src/main/java/com/dl/officialsite/wish/result/WishDetailResult.java
src/main/java/com/dl/officialsite/wish/result/WishLikeResult.java

feat:1. add curd wish controller 2. add apply like wish controller

wish feature

---

src/main/java/com/dl/officialsite/wish/Wish.java
src/main/java/com/dl/officialsite/wish/WishApply.java
src/main/java/com/dl/officialsite/wish/WishController.java
src/main/java/com/dl/officialsite/wish/WishLikeRepository.java
src/main/java/com/dl/officialsite/wish/WishService.java
src/main/java/com/dl/officialsite/wish/params/AddWishParam.java
src/main/java/com/dl/officialsite/wish/params/ApplyWishParam.java
src/main/java/com/dl/officialsite/wish/params/EditWishParam.java
src/main/java/com/dl/officialsite/wish/result/WishDetailResult.java

feat:1. add curd wish controller 2. add apply like wish controller

feat:1. add curd wish controller 2. add apply like wish controller

---

src/main/java/com/dl/officialsite/wish/Wish.java
src/main/java/com/dl/officialsite/wish/WishController.java
src/main/java/com/dl/officialsite/wish/WishRepository.java
src/main/java/com/dl/officialsite/wish/WishService.java
src/main/java/com/dl/officialsite/wish/job/WishXxlJob.java
src/main/java/com/dl/officialsite/wish/params/AddWishParam.java

feat:1. add updateWishTokenAmount xxljob

feat:1. add updateWishTokenAmount xxljob

---

src/main/java/com/dl/officialsite/login/filter/LoginFilter.java
src/main/java/com/dl/officialsite/wish/Wish.java
src/main/java/com/dl/officialsite/wish/WishApply.java
src/main/java/com/dl/officialsite/wish/WishApplyRepository.java
src/main/java/com/dl/officialsite/wish/WishController.java
src/main/java/com/dl/officialsite/wish/WishService.java
src/main/java/com/dl/officialsite/wish/config/TokenDeserializer.java
src/main/java/com/dl/officialsite/wish/params/AddWishParam.java
src/main/java/com/dl/officialsite/wish/params/ApplyWishParam.java
src/main/java/com/dl/officialsite/wish/result/WishDetailResult.java

feat:add two wish Field

---

src/main/java/com/dl/officialsite/member/Member.java
src/main/java/com/dl/officialsite/wish/WishController.java
src/main/java/com/dl/officialsite/wish/WishService.java

feat:add liked field to Member info

feat:add liked field to Member info

---

src/main/java/com/dl/officialsite/member/Member.java
src/main/java/com/dl/officialsite/wish/WishService.java

fix: 1. delete wish have not in contract .

fix: 1. delete wish have not in contract .

---

src/main/java/com/dl/officialsite/wish/domain/Wish.java
src/main/java/com/dl/officialsite/wish/enums/WishStatusEnum.java

fix: 1. add like feature 2. add share with wish

fix: 1. add like feature 2. add share with wish

---

src/main/java/com/dl/officialsite/wish/WishController.java
src/main/java/com/dl/officialsite/wish/WishService.java
src/main/java/com/dl/officialsite/wish/params/ApplyWishParam.java
src/main/java/com/dl/officialsite/wish/params/DonationWishParam.java

fix: 1. add apply wish

---

src/main/java/com/dl/officialsite/wish/WishService.java

fix: 1. update wish liked status

fix: 1. update wish liked status

---

src/main/java/com/dl/officialsite/sharing/Share.java

fix: 1. wish add share field

---

src/main/java/com/dl/officialsite/wish/WishService.java

fix: 1. use scheduled not xxl-job

fix: 1. use scheduled not xxl-job

---

src/main/java/com/dl/officialsite/wish/WishService.java
src/main/java/com/dl/officialsite/wish/domain/Wish.java
src/main/java/com/dl/officialsite/wish/result/WishDetailResult.java

fix: 1. add settle user

---

src/main/java/com/dl/officialsite/wish/WishService.java
src/main/java/com/dl/officialsite/wish/domain/Wish.java

fix: 1. update date to LocalDateTime

fix: 1. update date to LocalDateTime

---

src/main/java/com/dl/officialsite/wish/WishService.java

fix: 1. fix finish status

---

src/main/java/com/dl/officialsite/wish/WishService.java

fix: 1. fix data not vaild

---

src/main/java/com/dl/officialsite/wish/WishService.java
src/main/java/com/dl/officialsite/wish/params/QueryWishParam.java

feat: sort by createTime and amount

feat: sort by createTime and amount

---

src/main/java/com/dl/officialsite/wish/WishController.java
src/main/java/com/dl/officialsite/wish/WishService.java

fix: fix list page and update wish

fix: fix list page and update wish

---

src/main/java/com/dl/officialsite/login/filter/LoginFilter.java

feat: add wishlist for no login

feat: add wishlist for no login
